---
- hosts: myec2
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull app image
      docker_image:
        name: my-dockerhub-username/myapp:latest

    - name: Run app container
      docker_container:
        name: myapp
        image: my-dockerhub-username/myapp:latest
        state: started
        ports:
          - "8081:3000"
